#!/bin/sh
fancy_echo() {
  local fmt="$1"; shift

  printf "\n$fmt\n" "$@"
}

fancy_echo "Welcome to Danny's macOS Installer"
echo "-------------------------------------"
echo

# Get admin password & store in $passwd
echo -n "Admin Password: "
stty -echo
read passwd
stty echo
echo

# Run homebrew and ruby scripts
source brew.sh
source ruby.sh

# Update NVM / Node etc
fancy_echo "Updating NVM/NPM..."

nvm install latest
nvm -v

npm update npm -g
npm update -g

# Install dotfiles
fancy_echo "Installing dotfiles..."
git clone http://github.com/dannysmith/dotfiles $HOME/.dotfiles
cd $HOME && rcup

# Vim Plugins
echo "Installing Vim Plugins..."
curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fancy_echo "Running VimPlug Commands..."

vim :silent! +PlugInstall +qall
vim :silent! +PlugClean +qall

# Run mac-specific scripts.
source macos.sh
source macos-applescripts.sh

# Change Shell to zsh
chsh -s "$(which zsh)"
